snapshot-labs/pineapple

package.json
src/providers/infura.ts
src/rpc.ts
yarn.lock

Closes #14
Adds Infura provider.
To test add `INFURA_PROJECT_ID` and `INFURA_PROJECT_SECRET` environment variables.
Note: Using `ipfs-http-client` 0.56.0 instead of latest 0.57.0 because `exports` field in that version is broken.

feat: add Infura provider

---

package.json
yarn.lock

This also bumps `node-fetch` that had issue that caused previous crashes.

chore: upgrade cross-fetch to 3.1.6

---

package.json
src/index.ts
src/proxy.ts
src/rpc.ts
src/sentry.ts
src/upload.ts
yarn.lock

Send errors to sentry
- Add logger to log all uncaught errors
- Refactor code to send caught errors to sentry, instead of `console.log`

feat: send errors to sentry

---

src/upload.ts

When uploading a file too big, it returns an unhandled 500 error from express.
We should try/catch the error, and return the error in JSON RPC format, like the other errors.
Fix #140 
Fixes PINEAPPLE-1
- Move multer from middleware to being inside the request, so we can have access to the error object
- Return an JSON RPC error with a meaninful message when the file is too large
- Use postman to test file upload
- BEFORE fix: it returns an unhandled 500 HTML error
- AFTER fix: it returns a handled JSON RPC error

fix: fix file size exceeding limits error not being handled

---

README.md
src/rpc.ts
src/upload.ts
src/utils.ts
test/e2e/upload.test.ts

Current error message are more code than message, and not ready to be shown directly to consumer. 
Improve error message, so they can be shown directly on the UI
A well formatted error response will enable us to re-throw it on pineapple.js https://github.com/snapshot-labs/pineapple.js/pull/14
- Improve error messages
- Return the error message in the JSON-RPC `message` field instead of data (this field was always returning `unauthorized`, no matter the error)
- Return 400 error code instead of 500 for user input errors
- Add description of error code in README
- Try to test the /upload endpoint with various failing scenario
- The error message should be more useful, and formatted

fix: improve error message

---

src/rpc.ts
test/e2e/rpc.test.ts

Fixes #150 
Fixes PINEAPPLE-5 
Fix error when the post body is malformed (missing the `params` key)
- Also try/catch the AWS cache function, so it fail transparently when the credentials are not set
- Add test for the JSON upload enpdoint

fix: catch and return 400 error when payload is invalid

---

.github/dependabot.yml
package.json
src/index.ts
src/metrics.ts
src/providers/4everland.ts
src/providers/fleek.ts
src/providers/index.ts
src/providers/infura.ts
src/providers/pinata.ts
src/providers/web3storage.ts
src/proxy.ts
src/rpc.ts
src/stats.ts
src/upload.ts
yarn.lock

This PR install the metrics system
- Install the basic @snapshot-labs/snapshot-metrics package
- Instrument each providers response time, upload size and number of uses
- Instrument each gateway response time and number of uses
- Remove redundant timer inside each provider
- Remove dependabot
- Remove the `stats` global variable (not needed anymore, since we can track the same data from dashboard, and they're not reset on each restart)
Requires #146 
Fixes PINEAPPLE-4
- Visit `http://localhost:3003/metrics`
- It should show the basic metrics
- Upload one image/json
- Visit the metrics endpoint again
- It should show the custom metrics for providers (`providers_upload_duration_seconds` , `providers_upload_size` and `providers_return_count`)
- Visit …

feat: add metrics

---

src/metrics.ts
src/providers/index.ts
src/proxy.ts

This PR adds 2 new gauges to monitor the number of outgoing open connections, triggered by async requests.
Trying to debug, and confirm whether the current memory leaks issue is coming from async outgoing requests

fix: instrument the number of open outgoing connections

---

.github/dependabot.yml

This PR add back dependabot, but only enable it for package published by @snapshot-labs

chore: add dependabot for orgs only package

---

src/providers/infura.ts

For unknown reasons, the Infura provider stop returning responses in a timely manner
The upload time keep increasing, and queries keep getting queued, until the process hit an out-of-memory error, and restart.
After the restart, Infura does not have any issues, despite receiving more traffic than before the restart.
Fix #164 
Fix [SNAPSHOT-SEQUENCER-H](https://snapshot-labs.sentry.io/issues/4415715774/?referrer=github_integration)
Add a `timeout` of 10s to infura upload. Average upload time is between 3s and 4s.
- Add 10s timeout to infura
- N/A

fix: add timeout to infura upload

---

src/providers/index.ts

The `uploadToProviders` process all providers passed to it. That list is a constant, and does not take into account providers that were disabled because of missing credentials.
Skip providers that were not configured (missing credentials from .env)
- Add a filter to only process providers properly configured
- Fix web3Storage provider name casing

fix: skip disabled providers

---

src/providers/index.ts

This PR catch errors thrown by provider's upload function.

chore: capture provider upload errors

---

src/metrics.ts
src/providers/index.ts
src/providers/utils.ts
src/rpc.ts
src/upload.ts

This PR instrument the number of active providers per upload type (image/json)
- Move some code to `providers/utils.ts`: to avoid import loop
- End all metric HELP with a dot (`.`): follow best practice
- Add `type` (image/json) to `providers_upload_size` metrics
- Add `type` (image/json) to `providers_upload_duration_seconds` metrics

chore: instrument count of active providers per type

---

src/metrics.ts
src/providers/index.ts
src/rpc.ts
src/upload.ts

Some provider metrics are not labeled by type (json/image). 
- Add the `type` label to remaining providers metrics without it 
- Add `type` label to all remaining providers metrics without it 
- Migrate the `providersInstrumentation` middleware declaration inside metrics.ts. Inside of using of declaring the middleware usage next to each router, we move it inside the metrics.ts file, and use a kind of hook system to attach it to the correct route. This will reduce the metrics code footprint, instrumentation code should the most unobtrusive possible.
- Upload some JSON and image (via postman or other way)
- Visit `http://localhost:3000/metrics`
- The `providers_return_count` metric should have a new `type` label value, with value either `image` of `json`

chore: add provider type to all providers metrics

---

src/metrics.ts
src/providers/index.ts
src/proxy.ts

Fix the `finally` not being executed due to error thrown inside catch block. Fixed by returning  a `Promise.reject` instead
- Add `status` label to `ipfs_gateways_response_duration_seconds` and `providers_upload_duration_seconds` metrics => differentiate metrics for requests that succeed/failed
- When the error is a well formatted JSON response, send it to Sentry as contexts => avoid error type `Non-Error exception captured with keys: details, reason`

fix: fix finally block not executed

---

src/proxy.ts
test/e2e/proxy.test.ts

The `/ipfs/*` endpoint is currently returning json content. 
But when the given CID is something else than a JSON file, the endpoint fail, with a timeout error (`await response.json()` is timing out)
- Return a 400 error when the content-type is not a json file
- reject the promise when the content-type is not matching a json content type
- reject the promise when parsing the body as json is failing.
- Run the tests
- http://localhost:3000/ipfs/bafkreib5epjzumf3omr7rth5mtcsz4ugcoh3ut4d46hx5xhwm4b3pqr2vi should return a json content
- http://localhost:3000/ipfs/bafybeie2x4ptheqskiauhfz4w4pbq7o6742oupitganczhjanvffp2spti should return a 400 error

fix: IPFS gateway should return only json content

---

src/providers/index.ts

When capturing and sending a string to sentry, it'll show on Sentry as `<anonymous>` (See example here https://snapshot-labs.sentry.io/issues/4457737309/?project=4505506861023232&query=&referrer=issue-stream&statsPeriod=14d&stream_index=1)
Send an error object instead of string
- Wrap the string into an Error object, so that Sentry can show the correct title
- Avoid logging Timeout error (fix #173 )
- N/A

chore: send error object to Sentry

---

src/upload.ts

Following https://discord.com/channels/955773041898573854/1147615869908828180/1147830092869935157
Verbose logs should be removed, as not providing much more insight than the dashboard, and just creating noise preventing finding errors from the logs

chore: remove verbose logs

---

src/proxy.ts
src/rpc.ts

This PR fix the wrong cache key, when trying to cache the JSON at the same time as pinning
The `/ipfs/ID` endpoint is looking for a cache in the `/cache` folder, and expecting a key hashed with sha256

fix: fix wrong cache key when caching json on pin

---

package.json
yarn.lock

Upgrade snapshot-metrics to 1.3.0
Replacing https://github.com/snapshot-labs/pineapple/pull/185 , because tests are failing when PR open by dependabot. Does not seems to detect the env var

chore: upgrade snapshot-metrics to 1.3.0

---

src/aws.ts
test/e2e/proxy.test.ts

- Check that aws cache client is set before using
- Fix test to skip if the cache credentials are missing

chore: make cache optional

---

test/unit/providers/index.test.ts

Web3Storage API has been sunset on January 9th 2024.
We don't use anymore, but still testing it, which stopped working.
This PR removes web3Storage from test suite

chore: stop testing web3storage

---

src/proxy.ts

We use TheGraph IPFS for EVM indexing, because other IPFS services are not resolving well with Subgraphs.
This however becomes a problem, because TheGraph doesn't have public API, so:
1. Trying to access proposal/vote metadata through browser (via View metadata) might not work.
2. Migrating from subgraph to other indexer (Checkpoint) is problematic, because we might not be able to access old data.
We can however access files from TheGraph's IFPS via API.
Right now TheGraph will be called every time we try to access any file via Pineapple. Should it be conditional (via `graphipfs=true` in query params? In that case we would need to update our Checkpoint indexer to include that flag and on UI also add it when trying to view metadata for EVM entities.
1. This doesn't resolve: …

feat: resolve files from TheGraph IPFS API
